/** Shared first-run contract for the site and the MCP tool. The host owns local files. */
export const LOCAL_ONBOARDING_PROMPT = `Let's set up 3xrep for my sales work on this computer. Call the 3xrep start_onboarding tool, then guide me one step at a time. Do not analyze a deal yet.`;

export const LOCAL_ONBOARDING_GUIDE = `3xrep first run — desktop with local folder access only.

The MCP connection cannot send the first message on its own. The user has started this conversation; now lead the setup. Ask one small group of questions at a time, wait for answers, and let the user correct your summary. Do not ask for a password, connector key, customer transcript, or payment card.

1. Meet the person: name they want you to use, job title, whether they sell directly or manage a team, and what they want help with first.
2. Understand the company: company name and website, what they sell, to whom, usual sales cycle, and any important constraints. Ask only what the user knows. Summarize and ask them to correct it. The website is a clue, not a source of verified claims. After confirmation, call set_org_profile with company_url and a short corrected company_blurb if a URL was supplied. Do not send the person's name or role to that organization-level tool.
3. Ask: "Which folder on this computer should hold your 3xrep working memory?" The user must choose or authorize a local folder in this desktop host. Some hosts require choosing it when the task starts; if one is already attached, confirm it with the user now. Use only the host's local file tools. Do not use a cloud project, cloud drive, or a path supplied by the MCP server. If local file access is unavailable, explain how to open a desktop task with a connected folder, and pause file setup. Never claim that files were written when they were not. Confirm the chosen folder before writing.
4. In the authorized folder, create a 3xrep subfolder if needed. Read existing 3xrep files first; update them rather than overwriting earlier work. Create person.md (name, role, goals), company.md (confirmed offer, buyers, cycle, unknowns), day.md (date, current priorities, open questions, next actions), and deals/ for short per-deal notes. Use Markdown. Keep summaries brief, date facts, mark unknowns, and distinguish buyer quotes from the user's interpretation. Do not copy full calls, emails, secrets, or the MCP key into these files. Tell the user the exact files created and where they are. If a write fails, say so and do not mark setup complete.
5. Then help the user connect their CRM, email, and calendar in this assistant. Ask which CRM they use. Check which connectors are actually available; do not claim access until a real read succeeds. Start without a CRM if necessary: the user can bring notes into the chat. Gmail and Calendar help the morning plan but are not required for one-deal advice. Never ask for credentials in chat.
6. Invite the first real task: one deal, or today's plan. Read the local memory first. Use 3xrep tools for strategy. After each useful exchange, update day.md and the relevant deal note with verified facts, decisions, remaining questions, and the next step. Use a stable CRM opportunity ID for a deal filename when available; otherwise use a clearly provisional local filename and reconcile it when an ID arrives. Do not send a message or change the CRM without the user's approval.

On later sessions, read the local 3xrep files before asking repeated setup questions. The user can change the folder and correct or delete these files. 3xrep's separate server-side memory is a small record of missing deal evidence; these local Markdown files are the user's working notes.`;
