export { scoreDeal } from "./audit";
export { CONTRAT } from "./contrat";
export type { Etat } from "./etat";
export { layerOf } from "./layer";
export { METHODES } from "./lexique";
export { methodeLookup } from "./lookup";
export { runMoteur } from "./moteur";
export { nextQuestion } from "./next-question";
export { objectionMap } from "./objection-map";
export { CONTRAT_PIPE, pipeReview } from "./pipe";
export type { Contradiction, PipeDeal, PipeReview, TrouSystemique } from "./pipe";
export { rattacher, RATTACHER_MAX } from "./rattacher";
export type { Audit, DealInput, Geste, GesteId, Layer, Trou } from "./types";
