/** Public definitions and 3xrep's explicit adaptation. No claim of full automation. */
export const METHOD_GUIDANCE: Record<string, { source: string | null; usage: string; adaptation: string }> = {
  bant: { source: "https://www.salesforce.com/blog/what-is-bant-lead-generation/", usage: "Budget, autorité, besoin, échéance : qualifier le dossier.", adaptation: "Grille par défaut pour un cycle court ou inconnu. Ce choix est provisoire sans contexte." },
  spiced: { source: "https://winningbydesign.com/spiced-framework/", usage: "Situation, Pain, Impact, Critical Event, Decision. Decision comprend les critères, personnes et processus.", adaptation: "Cycle moyen déclaré. L’autorité n’est pas une sixième lettre. Le détecteur chiffré ne couvre pas tous les impacts qualitatifs." },
  meddic: { source: "https://meddicc.com/meddpicc-sales-methodology-and-process", usage: "Metrics, Economic Buyer, Decision Criteria, Decision Process, Identify Pain, Champion.", adaptation: "Cycle complexe. Échéance ajoutée par 3xrep ; aucune case cochée ne vaut une preuve." },
  meddpicc: { source: "https://meddicc.com/meddpicc-sales-methodology-and-process", usage: "Étend MEDDIC avec Paper Process et Competition. Distinguer le choix du fournisseur et le chemin du contrat.", adaptation: "Cycle complexe avec passage contractuel ou concurrence. Les priorités sont propres à 3xrep." },
  spin: { source: "https://www.huthwaiteinternational.com/spin-methodology", usage: "Situation, Problem, Implication, Need-payoff : approfondir une découverte, sans séquence mécanique.", adaptation: "Guidage de conversation. Les questions concrètes viennent des pièces manquantes, pas d’une simulation complète de SPIN." },
  crac: { source: null, usage: "Creuser, reformuler, argumenter, contrôler la réponse à une objection.", adaptation: "Version opératoire 3xrep. Pas de source canonique revendiquée ; ne pas déduire la cause du refus sans preuve." },
  bac: { source: null, usage: "Bénéfice, avantage, caractéristique : relier la démonstration au besoin.", adaptation: "Version opératoire 3xrep. Pas de source canonique revendiquée ; aucune caractéristique produit inventée." },
  "gap-selling": { source: null, usage: "Explorer l’écart entre situation actuelle et situation souhaitée.", adaptation: "Résumé inspiré de Gap Selling, pas une exécution complète ni une certification. Source primaire à compléter." },
  contreparties: { source: null, usage: "Relier une concession à une contrepartie explicite.", adaptation: "Règle 3xrep de négociation, pas une méthode propriétaire revendiquée." },
};
